todo:
  keyword: ["@todo", "TODO"] # string|string[]
  bodyKeyword: ["@body", "BODY"] # string|string[]
  blobLines: 5                # number|boolean, 0 or false to disable
  autoAssign: false            # string|string[]|boolean
  label: false                 # boolean|string|string[]
  reopenClosed: true          # boolean
