# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

sudo: false
cache: packages
language: r
r:
  - oldrel
  - release
  - devel

r_github_packages:
  - r-lib/pkgdown

after_success:
  - Rscript -e 'covr::codecov()'

r_check_args: "--as-cran --run-dontrun"

deploy:
  provider: script
  script: pkgdown::deploy_site_github(new_process=FALSE)' || true
  skip_cleanup: true
  on:
    branch: master
    condition: "$TRAVIS_R_VERSION_STRING = release"
